export type RoomItem = {
  banLa: boolean;
  banUi: boolean;
  bep: boolean;
  dieuHoa: boolean;
  doXe: boolean;
  giaTien: number;
  giuong: number;
  hinhAnh: string;
  hoBoi: boolean;
  id: number;
  khach: number;
  maViTri: number;
  mayGiat: boolean;
  moTa: string;
  phongNgu: number;
  phongTam: number;
  tenPhong: string;
  tivi: boolean;
  wifi: boolean;
};
