import type { Metadata } from 'next';
import { Toaster } from 'sonner';

import Header from '@components/header/header';

import './globals.css';
import QueryProvider from './queryProvider';

export const metadata: Metadata = {
  title: 'Trustify | Nhà nghỉ dưỡng',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen overflow-y-auto">
        <QueryProvider>
          {children}
          <Header />
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                width: 'max-content',
                minWidth: '150px',
                minHeight: '60px',
                padding: '16px',
                borderRadius: '8px',
                fontSize: '16px',
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
