import type { Metadata } from 'next';
import { Toaster } from 'sonner';

import Header from '@components/header/header';

import './globals.css';
import QueryProvider from './queryProvider';

export const metadata: Metadata = {
  title: 'Trustify | Nhà nghỉ dưỡng',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen overflow-y-auto">
        <QueryProvider>
          {children}
          <Header />
          <Toaster
            position="top-right"
            toastOptions={{
              style: { width: 'fit-content' },
              className:
                'min-h-[60px] p-4 rounded-lg text-base break-words whitespace-normal max-w-[90vw] md:max-w-[420px]',
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
